resource_registry:
  OS::TripleO::ComputeOvsDpdkSriov::Net::SoftwareConfig: nic-configs/nicpart/computeovsdpdk-nicpartition.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/nicpart/controller-nicpartition.yaml

parameter_defaults:
  NeutronPhysicalDevMappings: ["sriov1:eno3", "sriov2:eno4"]
  NovaPCIPassthrough:
  - devname: "eno3"
    trusted: "true"
    physical_network: "sriov1"
  - devname: "eno4"
    trusted: "true"
    physical_network: "sriov2"

