resource_registry:
  OS::TripleO::ComputeOvsDpdkSriov::Net::SoftwareConfig: nic-configs/computeovsdpdksriov.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ControllerSriov::Net::SoftwareConfig: nic-configs/controller.yaml

parameter_defaults:
  NeutronTunnelTypes: 'geneve'
  NeutronNetworkType: ['geneve', 'vlan']
  NeutronEnableDVR: false
  NeutronPluginExtensions: "port_security,qos,segments,trunk,placement"
  NeutronSriovAgentExtensions: "qos"
  #NeutronTunnelTypes: 'vxlan'
  #NeutronNetworkType: ['vxlan', 'vlan']

  NeutronPhysicalDevMappings: ["sriov1:eno3", "sriov2:eno4"]

  NovaPCIPassthrough:
  - devname: "eno3"
    trusted: "true"
    physical_network: "sriov1"
  - devname: "eno4"
    trusted: "true"
    physical_network: "sriov2"

