resource_registry:
  OS::TripleO::ComputeSriov::Net::SoftwareConfig: nic-configs/computesriov.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ControllerSriov::Net::SoftwareConfig: nic-configs/controller.yaml

parameter_defaults:
  NeutronBridgeMappings: 'datacentre:br-ex,sriov1:br-link1,sriov2:br-link2'
  NeutronFlatNetworks: 'datacentre,sriov1,sriov2'
  NeutronPhysicalDevMappings: ["sriov1:eno3", "sriov2:eno4"]
  NovaPCIPassthrough:
  - devname: "eno3"
    trusted: "true"
    physical_network: "sriov1"
  - devname: "eno4"
    trusted: "true"
    physical_network: "sriov2"

