resource_registry:
  OS::TripleO::ComputeSriovOffload::Net::SoftwareConfig: nic-configs/offload/computesriov-offload.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/offload/controller-offload.yaml

parameter_defaults:
  NovaPCIPassthrough:
  - devname: "ens1f0"
    physical_network: "sriov1"
  - devname: "ens1f1"
    physical_network: null

